In [1]:
import numpy as np

In [2]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
arrzero = np.zeros(5)
print(arrzero)

[0. 0. 0. 0. 0.]


In [5]:
arrones = np.ones(5)
print(arrones)

[1. 1. 1. 1. 1.]
