In [2]:
import numpy as np

In [3]:
# Use randint to generate a 3 by 3 array of random integers between 10 and 100
i = np.random.randint(10,100,(3,3))

print(i)

[[19 23 88]
 [21 56 34]
 [56 20 63]]


In [4]:
# Type the code to print the size of array i
print(i.size)

9


In [5]:
# Type the code to print the shape of array i

print(i.shape)

(3, 3)


In [7]:
# Type the code to print the number of dimensions of the array

print(i.ndim)

2


In [10]:
# Print the third element on the first row of the array

print(i[0,2])

88


In [9]:
# Print the second element on the third row of the array

print(i[2,1])

20


In [12]:
# Multiply the elements in array i by 10 and assign the results to a new variable

b = i * 10
# Print the new variable
print(i)
print(b)

[[19 23 88]
 [21 56 34]
 [56 20 63]]
[[190 230 880]
 [210 560 340]
 [560 200 630]]


In [14]:
# Create a 3 by 5 array of random floats between 0 and 50
f = np.random.random([3,5])*50
print(f)

[[43.98021862 41.65497087 16.71783026 44.66871048  2.34275733]
 [11.78841536  9.77310893 43.67326955  0.41098258 12.45414817]
 [48.21083914 25.55320689 30.93972456 33.04733464 15.13835237]]


In [15]:
# Create an array of four strings

s = np.array(["apple", "banana", "cherry", "grapes"])
print(s)

['apple' 'banana' 'cherry' 'grapes']
