In [1]:
import numpy as np

In [2]:
height_inches = [66,68,71,64,61,74,64,65,70,71]
arr = np.array(height_inches)
print(arr)

[66 68 71 64 61 74 64 65 70 71]


In [9]:
height_inches = [66,68,71,64,61,74,64,65,70,71]
height_inches = np.array(height_inches)
height_feet = height_inches / 12
print(height_feet)

[5.5        5.66666667 5.91666667 5.33333333 5.08333333 6.16666667
 5.33333333 5.41666667 5.83333333 5.91666667]


In [11]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
arr2 = np.random.randint(0, 100, 10)
print(arr2)

[36 47 63  2 89  3 87 13 81 61]


In [13]:
arr3 = np.arange(0, 76, 5)
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]
